when:
  branch: main
  event: [push, pull_request, manual]

steps:
  - name: lint
    image: ghcr.io/cirruslabs/android-sdk:36
    commands:
      - ./gradlew lint --no-daemon
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

  - name: test
    image: ghcr.io/cirruslabs/android-sdk:36
    commands:
      - ./gradlew test --no-daemon
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

  - name: publishToMavenLocal
    image: ghcr.io/cirruslabs/android-sdk:36
    commands:
      - ./gradlew publishToMavenLocal --no-daemon
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"